FROM alpine:20220328

ARG USER=browser

RUN apk add --no-cache epiphany gst-plugins-good gst-plugins-bad mesa-dri-swrast font-opensans adwaita-icon-theme && \
    adduser -D $USER

USER $USER

ENV DISPLAY=host.docker.internal:0.0

CMD epiphany