FROM docker-gui

RUN \
    apt update && \
    apt install -y openssh-server

RUN sed -i 's/#*X11Forwarding.*/X11Forwarding yes/' /etc/ssh/sshd_config
RUN sed -i 's/#*X11UseLocalhost.*/X11UseLocalhost no/' /etc/ssh/sshd_config
RUN useradd -m testuser -p $(openssl passwd 1234)

EXPOSE 22

CMD service ssh start ; bash